# -*- coding: utf-8 -*-
"""1D Heat Equation Solver (FDM).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kGpgYHs8_OUn8TT8Ipe45b0VoHDWZD18
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# PARAMETERS
length = 1.0          # Length of rod
time_total = 0.5      # Total simulation time
alpha = 0.01          # Thermal diffusivity

nx = 50               # Spatial points
nt = 500              # Time steps

dx = length / (nx - 1)
dt = time_total / nt

# STABILITY CHECK
stability_limit = dx**2 / (2 * alpha)

if dt > stability_limit:
    print("WARNING: Stability condition violated!")
    print(f"dt = {dt:.5f} should be <= {stability_limit:.5f}")
else:
    print("Stability condition satisfied.")

# INITIALIZATION
x = np.linspace(0, length, nx)

# Initial condition: sine wave
u = np.sin(np.pi * x)

# Boundary conditions
u[0] = 0
u[-1] = 0

# FUNCTION: ONE TIME STEP UPDATE
def step(u):
    un = u.copy()
    for i in range(1, nx - 1):
        u[i] = un[i] + alpha * dt / dx**2 * (un[i+1] - 2*un[i] + un[i-1])
    return u

# STATIC SIMULATION (FINAL RESULT)
u_static = u.copy()
for _ in range(nt):
    u_static = step(u_static)

# Plot final result
plt.figure(figsize=(8, 4))
plt.plot(x, u_static, label="Final Temperature")
plt.xlabel("Position")
plt.ylabel("Temperature")
plt.title("1D Heat Equation - Final State")
plt.legend()
plt.grid()
plt.show()


# ANIMATION SETUP
u_anim = np.sin(np.pi * x)
u_anim[0] = 0
u_anim[-1] = 0

fig, ax = plt.subplots(figsize=(8, 4))
line, = ax.plot(x, u_anim, color='blue')

ax.set_xlim(0, length)
ax.set_ylim(-1, 1)
ax.set_xlabel("Position")
ax.set_ylabel("Temperature")
ax.set_title("Heat Diffusion Over Time")
ax.grid()

# ANIMATION FUNCTION
def update(frame):
    global u_anim
    u_anim = step(u_anim)
    line.set_ydata(u_anim)
    return line,

# Create animation
ani = animation.FuncAnimation(
    fig,
    update,
    frames=200,
    interval=50,
    blit=True
)

plt.show()